title: Hello, world! I'm MoisÃ©s Omena
description: > # this means to ignore newlines until "baseurl:"
  This site is  focused Databases, Knowledge Discovery, Data Mining, 
  Data Warehouses e Business Intelligence as well as Agile Development 
  and Geographic Information Systems.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Moises Omena # add your name
author-img: mo_400x400.png # add your photo
about-author: I am a data scientist focusing Databases, Knowledge Discovery, Data Mining, Data Warehouses e Business Intelligence as well as Agile Development and Geographic Information Systems. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
